# CI de Nivel 2 - Disparo agendado

# nome da 'pipeline'

name: 'Execução Agendada'

# regras de disparo (gatilho / trigger)
# gatilho do exec manual =  workflow_dispatch

on:
  schedule:
    - cron: '0 15 8 6 *' # 12:00 BRT de 08/06/2025

# trabalhos / tarefas dentro do pipeline = jobs

jobs:
  e2e-testes:
    #maquina que o job vai executar
    runs-on: ubuntu-latest

    #passos do script de build
    steps:
      # clone do projeto
      - uses: actions/checkout@v4

      #Instalação do Node.js
      - uses: actions/setup-node@v4
        with:
          node-version: 22.x # ou a versão que você preferir

      # Instalação do Yarn
      - name: Instalação do Yarn
        run: npm install -g yarn

      # Instalação das dependências
      - name: Instalação das dependências
        run: yarn

      # Instalação do Playwright
      - name: Instalação do Playwright
        run: yarn playwright install

      # executar os testes E2E
      - name: Executar os testes E2E
        run: npm run e2e
