# CI de Nivel 03 - Disparo após a conclusão de um pipeline

# nome da 'pipeline'

name: 'Execução por Deploy'

# regras de disparo (gatilho / trigger)
# gatilho do exec manual =  workflow_dispatch
# gatilho do exec agendada =  schedule
# gatilho do exec a partir de outro pipeline =  workflow_run

on:
  workflow_run:
    workflows: ['Execução Manual']
    types:
      - completed

# trabalhos / tarefas dentro do pipeline = jobs

jobs:
  e2e-testes:
    #maquina que ojob vai executar
    runs-on: ubuntu-latest

    #condicional - if
    #`$ { expressao }`
    # ==comparação

    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    #passos do script de build
    steps:
      # clone do projeto
      - uses: actions/checkout@v4

      #instalação do Node.js
      - uses: actions/setup-node@v4
        with:
          node-version: 22.x # ou a versão que você preferir

      # Instalação do Yarn
      - name: Instalação do Yarn
        run: npm install -g yarn

      # Instalação das dependências
      - name: Instalação das dependências
        run: yarn

      # Instalação do Playwright
      - name: Instalação do Playwright
        run: yarn playwright install

      # executar os testes E2E
      - name: Executar os testes E2E
        run: yarn run e2e

      - name: Upload de artefatos
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: relatorio
          path: ./playwright-report/
